# Generated by Django 4.2.11 on 2024-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('re_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Buy', max_length=200),
        ),
    ]
